### ISSUE TITLE
My popover flicks on scroll. 

### ISSUE THREAD

**Issue by Santoshah** [joejordanbrown/popover#62]
#### Bug, feature request, or proposal:
My popover stays fix on scroll. It stays on the top while scrolling. and when scroll back to top the width , right etc properties get update and flick the size of the box.

#### What is the expected behaviour?
It should have scroll up with the screen. And the width of the popup should remain the same.

#### What is the current behaviour?
It stays on the top and width is variable on scroll.

https://www.loom.com/share/f11b1ee192364a2fa461e0c292dd409b

####StackBlitz Template: https://mde-popover-2jwo6g.stackblitz.io

```
                <button mat-button class="btn-menu cart_button" [mdePopoverTriggerFor]="appPopover"
                mdePopoverTriggerOn="click" #popoverTrigger="mdePopoverTrigger" mdepopoverpositionx="before">
                    <mat-icon aria-hidden="false" matBadge="0" matBadgeColor="warn" matBadgeSize="small" aria-label="">shopping_cart</mat-icon>
                </button>

            
              <mde-popover #appPopover="mdePopover" [mdePopoverOverlapTrigger]="false" [mdePopoverCloseOnClick]="false">
                <mat-card style="max-width: 350px">
                  <mat-card-content>
                        <div class="cartproductlist" *ngFor="let cartItems of cartProductList">
                            <mat-card class="product-card text-left layout-horizontal"  fxFlex fxLayout="row">
                                <a href="javascript:void(0)" class="remove_me_from_cart"><i class="fa fa-trash"></i></a>
                                <img mat-card-image src="assets/img/products/frenchfries.png" alt="French Fries">
                                <mat-card-content>
                                    <p class="product-card-title">Kurkure</p>
                                    <p class="product-card-subtitle">New 2x110 g Multipack</p>
                                    <p class="product-rate">
                                        <span class="quantity_no_section">Quantity: <span class="quantity_no">1</span></span>
                                        <span class="price_idr">IDR: <span class="quantity_no">850.00</span></span>
                                    </p>
                                </mat-card-content>
                                

                            </mat-card>                            
                        </div>
                        <div class="total_wrap">
                            <span class="total_text">Total:</span>
                            <span class="total_amount">IDR <span class="total_price">1700.00</span></span>
                        </div>
                        <div class="button_wrap">
                            <button mat-button mat-flat-button class="btn-syp">CHECK OUT</button>	
                        </div>
                  </mat-card-content>
                </mat-card>
              </mde-popover>
```

**Comment by yoenispantoja** [comment]
In file: @material-extended\mde\fesm2015\material-extended-mde.js, move to line 788:
`overlayState.scrollStrategy = this._overlay.scrollStrategies.reposition();`
Try change the scrollStrategies. Instead of "reposition()" you can use .noop(), .close() or .block() by convenience
I learn this in this post:
https://blog.thoughtram.io/angular/2017/11/20/custom-overlays-with-angulars-cdk.html.

Good lucks

**Comment by joejordanbrown** [comment]
@Santoshah @yoenispantoja 

Sorry about the delay I replying, I missed this issue. 

I can confirm that I have added a scroll strategies option where you can change the scroll strategy. Once I have run some tests to make sure it's working properly I will release it.

**Comment by joejordanbrown** [comment]
@Santoshah @yoenispantoja 

The issue was related to a default option within the Angular CDK overlay position strategy, so the `reposition()` should still be used instead of `noop()` to fix this issue but requires `withLockedPosition(true)`. See API documentation here [ConnectedPositionStrategy](https://material.angular.io/cdk/overlay/api#FlexibleConnectedPositionStrategy).

I've hardcoded the fix for now but will provide a config option to set this to false if people require the popover to stay in viewport. The line of code that fixes this can be found [popover-trigger.ts:510](https://github.com/joejordanbrown/popover/blob/master/projects/material-extended/mde/src/lib/popover/popover-trigger.ts#L510)

Let me know if you have any questions or issues.
