### ISSUE TITLE
How can I close the popover when I leave the trigger?

### ISSUE THREAD

**Issue by BeckhamL** [joejordanbrown/popover#70]
#### What are the steps to reproduce?

Provide a working example using StackBlitz (or similar) to reproduce the problem.
StackBlitz Template: https://stackblitz.com/fork/mde-popover

**Comment by joejordanbrown** [comment]
Hello @BeckhamL

You can use `closePopover()` method, see docs [here ](https://github.com/joejordanbrown/popover/blob/master/projects/material-extended/mde/src/lib/popover/popover.md#methods-1). 

Use like `popoverTrigger.closePopover()`, an example with a button has `(focusout)="popoverTrigger.closePopover()"`. 

See the demo here https://stackblitz.com/edit/mde-popover-close-on-focusout?file=app/app.component.html.

Let me know if that's what you needed.

**Comment by BeckhamL** [comment]
Yes, thank you so much!

**Comment by joejordanbrown** [comment]
@BeckhamL 

I think I understand what you mean now. 

You'd like to turn off the hover event on the popover because this keeps it open correct?

The easiest way to accomplish this is by disabling the trigger from managing events via `mdePopoverTriggerOn="none"` and then adding custom events using `(mouseenter)="popoverTrigger.openPopover()" (mouseleave)="popoverTrigger.closePopover()"`.

```html
<button [mdePopoverTriggerFor]="appPopover"
    mdePopoverTriggerOn="none" 
    (mouseenter)="popoverTrigger.openPopover()" 
    (mouseleave)="popoverTrigger.closePopover()"
    #popoverTrigger="mdePopoverTrigger">
  Show Popover
</button>

```

See the demo here https://stackblitz.com/edit/mde-popover-close-on-trigger-mouseleave-not-interactive?file=app/app.component.html.

Let me know if this solves your issue.

**Comment by BeckhamL** [comment]
Yes, this is exactly what I needed. Thank you so much!
